export const patieents = [{
        id: 1,
        Name: "Momen Mekki",
        MedicalID: 2021602183,
        Room: "A-422",
        Status: "under medical supervision",
        Condition: "ide",
        Patientinfo: {
            Age: 23,
            Gender: "Female",
            RegisterDate: "1-2-2020",
            Branch: "Aswan Sail",
            Nurse: "Shima hmed",
            Doctor: "Mostafa Mohamed",
        },
        MedicalConditon: {
            Disease: "Gban",
            History: "1-2-2020",
            OtherDiseases: "Gban 5ales",
            Diabeyic: false,
            Smoker: true,
        },
    },
    {
        id: 2,
        Name: "Disha",
        MedicalID: 2021602183,
        Room: "B-102",
        Status: "under medical supervision",
        Condition: "ide",
        Patientinfo: {
            Age: 25,
            Gender: "Female",
            RegisterDate: "10-5-2020",
            Branch: "Aswan Sail",
            Nurse: "Merna Antonios",
            Doctor: "Ahmed Mostafa",
        },
        MedicalConditon: {
            Disease: "Mared Nafsy",
            History: "1-2-2020",
            OtherDiseases: "Male",
            Diabeyic: true,
            Smoker: false,
        },
    },
    {
        id: 3,
        Name: "Motaz Samy",
        MedicalID: 2021602183,
        Room: "A-405",
        Status: "under medical supervision",
        Condition: "ide",
        Patientinfo: {
            Age: 21,
            Gender: "Male",
            RegisterDate: "7-9-2021",
            Branch: "Cairo",
            Nurse: "Nesren Gamal",
            Doctor: "Ahmed Foda",
        },
        MedicalConditon: {
            Disease: "Sessa sdsads",
            History: "1-2-2020",
            OtherDiseases: "Smmadsk",
            Diabeyic: false,
            Smoker: true,
        },
    },
    {
        id: 4,
        Name: "Momen Mekki",
        MedicalID: 2021602183,
        Room: "A-422",
        Status: "under medical supervision",
        Condition: "ide",
        Patientinfo: {
            Age: 23,
            Gender: "Famele",
            RegisterDate: "Male",
            Branch: "Male",
            Nurse: "Male",
            Doctor: "Male",
        },
        MedicalConditon: {
            Disease: 23,
            History: "Male",
            OtherDiseases: "Male",
            Diabeyic: true,
            Smoker: true,
        },
    },
    {
        id: 5,
        Name: "Momen Mekki",
        MedicalID: 2021602183,
        Room: "A-422",
        Status: "under medical supervision",
        Condition: "ide",
        Patientinfo: {
            Age: 23,
            Gender: "Male",
            RegisterDate: "Male",
            Branch: "Male",
            Nurse: true,
            Doctor: true,
        },
        MedicalConditon: {
            Disease: 23,
            History: "Male",
            OtherDiseases: "Male",
            Diabeyic: true,
            Smoker: true,
        },
    },
    {
        id: 6,
        Name: "Momen Mekki",
        MedicalID: 2021602183,
        Room: "A-422",
        Status: "under medical supervision",
        Condition: "ide",
        Patientinfo: {
            Age: 23,
            Gender: "Male",
            RegisterDate: "Male",
            Branch: "Male",
            Nurse: true,
            Doctor: true,
        },
        MedicalConditon: {
            Disease: 23,
            History: "Male",
            OtherDiseases: "Male",
            Diabeyic: true,
            Smoker: true,
        },
    }
];